// Generated by your build script
import { z } from 'zod';

export const TipSchema = z.object({
  title: z.string().min(1, "Title is required"),
  // The rest of your schema...
});

export type Tip = z.infer<typeof TipSchema>;